### ISSUE TITLE
Lags horribly when I try to drag 15000+ items at once.

### ISSUE THREAD

**Issue by Alucard648** [WohlSoft/ItemScene#1]
Title says almost all.
![system_specs](https://cloud.githubusercontent.com/assets/7596025/18682734/0782b196-7f76-11e6-975a-cd126bfa3eef.png)
 Also I am suggesting to add bottom status bar entry showing total number of elements selected.

**Comment by Wohlstand** [comment]
that because I wasn't implemented right frameskip, and to change a coordinates of all of 15000+ elements is need to fetch all of them and append mouse delta, but I think, need some another algorithm to do that faster

**Comment by Wohlstand** [comment]
I just added counter of selected elements (in the sub-window title), so, please retry and count number of elements.
Anyway, as idea to prevent lagging, I can instead actual moving just draw huge rectangle over everything (if feed back time is bigger than 20/30 milliseconds) around and do actual moving after mouse releasing. If keep in mind that over 15000/30000 elements are carried and processing of that is not so fast on bigger zoom. Modern 3D games (for example, GTA SA) in moments, when character flying on a plane, and view around is wide, actual objects aren't drawing: only terrain or big objects.

**Comment by Alucard648** [comment]
Speaking for preventing lagging, how about to implement an option to switch between "real-time" element dragging and "schematic rectangle over everything" dragging depending on total elements selected, just like Item count limit for in-editor animation rendering.
P.S. I noticed that in the demo dragging huge chunk of elements lags even if dragging is almost offscreen, unlike real PGE editor where if you select 12000+ items in a section, scroll the view so only several items left in view and then drag selected ites, there is almost no FPS drop.
Test level: https://yadi.sk/d/Ey4FmzQWvTXsB

**Comment by Wohlstand** [comment]
I wasn't meant depending to element selecting, I meant counting elapsed time while fetching elements, and in result, same selection group will work different on show and fast computer. But ya, I can implement toggling of that: auto, real-time, abstract rectangle. In PGE Editor is the inoptimal QGraphicsScene which I going completely replace with mine

**Comment by Wohlstand** [comment]
Just now I have replaced R-Tree with QuadTree indexing algorithm and performance has been boosted up!
![peek 2018-03-11 23-54](https://user-images.githubusercontent.com/6751442/37258368-ef3cb456-2587-11e8-8f2a-8a19c6c6bd0e.gif)
Check out the result (dev-build will be re-assembled). Some lag will be presented, but not so hard as was on R-Tree case.

**Comment by Alucard648** [comment]
35000 items deagged at once. 2-4 FPS. Higher if zoomed in. <10k items at once - work fine.

**Comment by Wohlstand** [comment]
Even this case is rarely reachable (most of regular SMBX level, and even a world map, has 2000~5000 elements in the section / area), I still look for a ways to optimize this. In result we would take a backend for custom Yandex-Maps as there are vector and has lots of elements on the scene, and there are don't render small elements on a wide views.

**Comment by Alucard648** [comment]
Indeed it is unlikely to have >16k elements in single section. The closest I have made is my Basalt Organ level which after some minor optimizations  has 11k elements in it`s only section. However there are more factors that can contribute to laggy rendering such as advanced textures, metatags, collision callbacks or special elements interaction.
EDIT: Have you seen SMBX levels with >15k elements in single section (blocks, BGOs, NPCs, warp entry/exits and physical enviropment zones total)?

**Comment by Wohlstand** [comment]
I have checked out of my levels set and I got biggest of them, and I have level file that has in one section:
* 7178 Blocks
* 3344 BGOs
* 557 NPCs
* 60 Physical Environment Zones

![_2018-03-15_00-34-40](https://user-images.githubusercontent.com/6751442/37432261-d8bc29f6-27e8-11e8-9679-e9eac20150d0.png)
In total 11139 copyable objects (not counted warp points and playable character points).

Anyway, by checking of max limits, possible ability for legacy SMBX level is 30234 objects in total level.
(16384 blocks + 5000 NPCs + 8000 BGOs + 200×2 Warp points + 450 Physical Environment zones)

**Comment by Wohlstand** [comment]
Okay, I do think, that would be left this as-is with QuadTree, mainly, the thing is intended to work with smaller areas at the same moment, but having an option to move/copy things at far zooms, which usually is not needed often, except to copy/paste the huge area or make an overview of the thing (here I could pause the animations when the zoom is father than given factor, etc.). At least, this is an editor that is fine with micro-lags during various macro actions around the stuff, etc. But, if that's really needed to work with huge areas often, then, make some optimizations like the shapes generating while moving the group rather than do the real-time move of huge areas, etc.

**Comment by Alucard648** [comment]
Indeed. If anyone would need such degree of optimization, he could file an issue ticket in Moondust Editor repository.
P.S. Item Scene demo download link fails to work.

**Comment by Wohlstand** [comment]
It works, also, Rednaxela at the side reported me failure of Codehaus too, seems a little offline moment was at the hosting :thinking: 
![Снимок экрана от 2021-07-22 09-58-04](https://user-images.githubusercontent.com/6751442/126600615-40cc2645-45a1-442f-838b-fe49ce32ea5d.png)

**Comment by Alucard648** [comment]
Thanks for fixing download. Good luck with finishing rest of TODO`s.

**Comment by Wohlstand** [comment]
I do plan to finally take it for work after the next stable release of the Moondust Project to start the Big Rebuild.
