### ISSUE TITLE
Wrong schematic rectangle dimensions when dragging items.

### ISSUE THREAD

**Issue by Alucard648** [WohlSoft/ItemScene#2]
1. Drag multiple items at once with rectangle selection.
2. Clear selection by clixking on empty spot.
3. Try to drag any singular item.
We get this:
![item_scene](https://cloud.githubusercontent.com/assets/7596025/21181170/a498a574-c20d-11e6-9d62-3c1509b821d7.png)

**Comment by Wohlstand** [comment]
That part still be WIP. I just need to add very small conditional function call to don't show this rect. This rectangle must be shown instead moving items if render lag has been detected. But while developing, it shown always.

**Comment by Alucard648** [comment]
As for latest build, this issue is no longer reproducible.
